apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - ssh:
        address: 10.0.0.1
        user: devops
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller
    - ssh:
        address: 10.0.0.2
        user: devops
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 10.0.0.3
        user: devops
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
  k0s:
    version: 1.29.2+k0s.0
    dynamicConfig: false
